[options]
# Database settings
db_host = db
db_port = 5432
db_user = odoo
db_password = myodoo
db_name = False

# Server settings
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/usr/src/odoo/addons,/usr/src/odoo/custom_addons
data_dir = /var/lib/odoo
#logfile = /var/log/odoo/odoo.log
log_level = info
log_handler = :INFO

# Development settings
#dev_mode = reload,qweb,werkzeug,xml,python
workers = 0
max_cron_threads = 1

# Server configuration
xmlrpc_port = 8069
longpolling_port = 8072
proxy_mode = False

# Security
admin_passwd = admin123

# Performance
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

# Localization
timezone = Asia/Tokyo
lang = ja_JP